// react-client/src/components/Register/index.js
import React, { useReducer, useState } from "react";
import { Link } from "react-router-dom";
import axios from "axios";
import registerReducer from "../../reducers/registerReducer";
import "./register.scss";

const initialState = {
  isRegistering: false,
  success: false,
  error: {},
  user: {}
};

const Register = () => {
  const [state, dispatch] = useReducer(registerReducer, initialState);
  const [username, setUsername] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  const postUser = user => {
    dispatch({ type: "REGISTER_REQUEST" });
    axios
      .post("http://127.0.0.1:5000/api/v1/users/register", user)
      .then(res =>
        dispatch({
          type: "REGISTER_SUCCESS",
          user: res.data.newUser
        })
      )
      .catch(err =>
        dispatch({ type: "REGISTER_FAILURE", error: err.response.data })
      );
    console.log(state);
  };

  const handleSubmit = event => {
    event.preventDefault();

    const newUser = {
      username,
      email,
      password
    };
    postUser(newUser);

    // setUsername("");
    // setEmail("");
    // setPassword("");
  };

  const handleUsernameChange = e => {
    setUsername(e.target.value);
  };
  const handleEmailChange = e => {
    setEmail(e.target.value);
  };
  const handlePasswordChange = e => {
    setPassword(e.target.value);
  };

  return (
    <div className="container">
      <div className="register">
        <h2 className="register-head">Sign Up</h2>
        <Link to="/login" className="have-account">
          Already have an account ?
        </Link>
        <form onSubmit={handleSubmit} className="signUpForm">
          <input
            type="email"
            name="email"
            value={email}
            onChange={handleEmailChange}
            className="signUpField"
            placeholder="Enter email"
          />
          <input
            type="text"
            name="username"
            value={username}
            onChange={handleUsernameChange}
            className="signUpField"
            placeholder="Enter username"
          />
          <input
            type="password"
            name="password"
            value={password}
            onChange={handlePasswordChange}
            className="signUpField"
            placeholder="Enter password"
          />
          <button type="submit" className="signUpField btn">
            Sign up
          </button>
        </form>
      </div>
    </div>
  );
};

export default Register;

// client/src/views/Register.vue
<template>
  <div class="container">
    <h1 class="register-header"></h1>
    <form action class="registerform">
      <input
        type="text"
        v-model="username"
        name="username"
        class="register-inputs"
        placeholder="Username"
      >
      <input type="text" v-model="email" name="email" class="register-inputs" placeholder="Email">
      <input
        type="password"
        v-model="password"
        name="password"
        class="register-inputs"
        placeholder="Password"
      >
      <button type="submit" class="register-btn">Create Account</button>
    </form>
  </div>
</template>

<script>
import axios from "axios";

export default {
  name: "Register",
  data() {
    return {
      username: "",
      email: "",
      password: ""
    };
  },
  methods: {
    register(e) {
      e.preventDefault();
      const newUser = {
        username: this.username,
        email: this.email,
        password: this.password
      };
      axios
        .post("/api/users/register", newUser)
        .then(res => {
          console.log("singed up");
        })
        .catch(error => {
          console.log(error);
        });
    }
  }
};
</script>

<style scoped>
</style>
